frontend/README.md

Add part in the README.md to inform about why and how to use docker in the frontend

docs: add guide to docker in frontend

---

.gitignore
backend/docker-compose.yml
backend/docker-volumes/scripts-sql/init.sql

Modificação do docker-compose para subir o banco de dados no docker, além de criar o script ddl para criação da estrutura do banco de dados.

feat: implementacao do banco de dados

---

backend/src/main/java/com/acadmap/model/LogExclusao.java
backend/src/main/java/com/acadmap/model/LogVeiculo.java
backend/src/main/java/com/acadmap/model/Usuario.java
backend/src/main/java/com/acadmap/model/VeiculoPublicacao.java

Eu ajustei os nomes do mapeamento das classes do 'Models' para serem exatamente iguais às entidades do banco de dados.

Os nomes do mapeamento das classes para o banco ajustados

---

backend/src/main/java/com/acadmap/controller/EventoController.java
backend/src/main/java/com/acadmap/model/DTO/EventoCreateDTO.java
backend/src/main/java/com/acadmap/model/Evento.java
backend/src/main/java/com/acadmap/repository/EventoRepository.java
backend/src/main/java/com/acadmap/service/EventoService.java

feat : adiciona repository, controller e service de Evento

---

backend/src/main/java/com/acadmap/controller/UsuarioController.java
backend/src/main/java/com/acadmap/model/AreaPesquisa.java
backend/src/main/java/com/acadmap/model/Usuario.java
backend/src/main/java/com/acadmap/repository/LogRepository.java
backend/src/main/java/com/acadmap/repository/UsuarioRepository.java
backend/src/main/java/com/acadmap/service/LogService.java
backend/src/main/java/com/acadmap/service/UsuarioService.java

Este PR adiciona a funcionalidade de cadastro de usuário, incluindo:
Criação do endpoint para cadastro de novo usuário.
Registro de log ao realizar o cadastro, permitindo rastreabilidade da operação.

feat(usuario): implementa cadastro de usuário com registro de log

---

backend/src/main/java/com/acadmap/model/entities/VeiculoPublicacao.java

Corrigindo serialização de veiculo

fix: serialização de veiculo

---

backend/src/main/java/com/acadmap/controller/EventoController.java
backend/src/main/java/com/acadmap/repository/UsuarioRepository.java
backend/src/main/java/com/acadmap/service/EventoService.java

Corrige serviço do requisito 17

fix: service de cadastro de eventos

---

.idea/AcadMap.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
backend/endpoint.md
backend/src/main/java/com/acadmap/service/EventoService.java
backend/src/main/resources/application.properties
q

Ajuste no corpo de requisição, retirando a necessidade de passar a classificação e adequaçãodefesa. Elas serão tratadas em outras RFS

refactor: ajuste no corpo de requisição de evento

---

backend/endpoint.md
backend/src/main/java/com/acadmap/controller/PeriodicoController.java
backend/src/main/java/com/acadmap/exception/GlobalExceptionHandler.java
backend/src/main/java/com/acadmap/exception/PeriodicoDuplicadoException.java
backend/src/main/java/com/acadmap/exception/PeriodicoDuplicadoResponse.java
backend/src/main/java/com/acadmap/model/dto/PeriodicoResponseDTO.java
backend/src/main/java/com/acadmap/model/dto/PeriodicoResquestDTO.java
backend/src/main/java/com/acadmap/model/dto/PeriodicoSimplesDTO.java
backend/src/main/java/com/acadmap/repository/PeriodicoRepository.java
backend/src/main/java/com/acadmap/service/EventoService.java
backend/src/main/java/com/acadmap/service/LogService.java
backend/src/main/java/com/acadmap/service/PeriodicoService.java

Realização do cadastro de Periódico, com o tratamento de duplicidade. Atualização do endpoint.md com os endpoint do cadastro de periódico.

feat: realizacao Requisito 21

---

backend/endpoint.md

Mudança de descrição do issn no endpoint.md

docs: alterando descrição de issn na requisicao

---

.idea/.gitignore
backend/docker-volumes/scripts-sql/05_extra.sql

assim como veículo de publicação.

feat: Adicionando mais exemplos para desenvolvimento.

---

backend/src/main/java/com/acadmap/controller/UsuarioController.java

PR referente à criação de uma função para retornar usuário específico com base no Id do usuário.

feat: criação de end point para retornar usuário específico

---

frontend/src/pages/RevisaoCadastroEvento.jsx
frontend/src/pages/ValidacaoPeriodico.jsx

Alterados o consumo de endpoint pelo front-end:
/api/eventos/cadastro → **/api/eventos**
/api/periodicos/cadastro → **/api/periodicos**

merge: front faz a chamada para novos endpoints 

---

.github/workflows/prod-ci.yml

adding ci/cd pipeline to the main

chore(env): created prod-ci.yml

---

frontend/src/components/AdequacaoDefesa.jsx

implementação do componente de visualização de categoria para defesas acadêmicas.

feat: RF-26

---

backend/src/main/java/com/acadmap/controller/PeriodicoController.java

Correção de import e nome de classes no Periodico Controller, o qual estava ocasionando em erro na inicialização do sistema.

bug: correcao de imports e nome de classe

---

backend/endpoint.md
backend/src/main/java/com/acadmap/model/dto/evento/EventoResumoListaDTO.java
backend/src/main/java/com/acadmap/model/dto/periodico/PeriodicoResumoListaDTO.java

Adicionando campos no retorno do rf 03

refactor: ajuste no retorno do RF03

---

backend/endpoint.md
backend/src/main/java/com/acadmap/controller/LogVeiculoController.java
backend/src/main/java/com/acadmap/model/dto/log_veiculo/LogVeiculoDTO.java
backend/src/main/java/com/acadmap/service/ListarLogVeiculoService.java

Implementação da listagem das informações registradas nos logs de auditoria e a documentação referente para uso

Implementação do Histórico de Auditoria

---

.github/workflows/prod-ci.yml

Updated Dockerfile path for frontend build and added BACK_API_URL to .env.

env: change ci/cd frontend Dockerfile and update .env variables

---

docker-compose.prod.yml
frontend/eslint.config.js
frontend/src/App.jsx
frontend/src/charts/GraficoAdequacaoDefesa.jsx
frontend/src/components/AuthProvider.jsx
frontend/src/components/FiltroEventosPeriodicos.jsx
frontend/src/components/FormularioCadastro.jsx
frontend/src/components/FormularioPeriodico.jsx
frontend/src/components/ListaFiltrosEventosPeriodicos.jsx
frontend/src/hooks/useAuthCheck.js
frontend/src/hooks/useLogger.js
frontend/src/hooks/usePendencias.js
frontend/src/hooks/userAuth.js
frontend/src/pages/AuditoriaLogs.jsx
frontend/src/pages/ConsultaEventosPeriodicos.jsx
frontend/src/pages/DetalhePendente.jsx
frontend/src/pages/RevisaoCadastroEvento.jsx
frontend/src/pages/ValidacaoPeriodico.jsx
frontend/src/pages/VisualizarEvento.jsx
frontend/src/pages/VisualizarPeriodico.jsx
frontend/src/schemas/CadastrarEventoSchema.ts
frontend/src/utils/apiUrl.js
frontend/src/utils/authFetch.js
frontend/src/utils/logger.js

* refactor: inserindo exemplo de resposta
* refactor: ajuste no corpo de requisição de evento
* feat(env): refactoring dockerfiles and compose
* fix: header only show right pages for the logged user
* fix: cadastro usuario obtem area e programas do back
* fix: fix cadastro evento path
* chore: request para criar evento no backend
* chore: tela de cadastro de eventos integrada com o backend
* chore: tela de cadastro de usuario integrada com o backend
* fix(front): melhoria das cores escolhidas para apresentacao no front
* feat: adiciona page de periodicos
* fix(front): melhorar visibilidade de elementos das telas
* fix(cadastroPeriodico): tela adequada ao mockup fornecido
* fix(visual): visual fixes in frontend to get near the mockup example
* chore: componente de representação de …

 merge(staging): minor changes into env (#238) (#240)
